version: "3.3"

services:

  app:

    container_name: wzml

    build:

      context: .

      dockerfile: Dockerfile

    command: bash start.sh

    restart: on-failure

    ports:

      - "80:80"
